In [2]:
import numpy as np

In [4]:
list1=np.array(range(0,24+1))
print(list1.shape)
mat1=list1.reshape(5,5)
print(mat1)

list2=np.array(range(100,400+100,100))
print(list2)
mat2=list2.reshape(2,2)
print(mat2)

p = np.array([0, 3])

print(mat1[0,p[0]],mat1[0,p[1]],mat1[p[1],[0]],mat1[p[1],p[1]])

mat1[0,p[0]]=mat2[0][0]
mat1[0,p[1]]=mat2[0][1]
mat1[p[1]][0]=mat2[1][0]
mat1[p[1]][p[1]]=mat2[1][1]

print(mat1)

(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[100 200 300 400]
[[100 200]
 [300 400]]
0 3 [15] 18
[[100   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [300  16  17 400  19]
 [ 20  21  22  23  24]]


In [6]:
mat1[p[...,None], p] = mat2
print(mat1)

[[100   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [300  16  17 400  19]
 [ 20  21  22  23  24]]
