In [1]:
import pandas as pd
from io import StringIO
import io
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
data="""SubjectID,Feat_1,Feat_2,Feat_X,Hr_count,Label
s0001,89,31,43,1,0
s0001,94,32,68,2,0
s0001,38,90,86,3,0
s0001,79,34,78,4,1
s0001,85,24,70,5,1
s0002,7 ,9 ,32,1,0
s0002,60,56,72,2,0
s0002,68,72,23,3,0
s0003,26,88,1 ,1,0
s0004,45,27,22,1,0
s0004,10,80,67,2,0
s0004,71,48,21,3,0
s0004,58,9 ,60,4,1
"""

df=pd.read_csv(io.StringIO(data),sep=",")
df.drop(columns='Hr_count',inplace=True)
encoder=LabelEncoder()
df['SubjectID']=encoder.fit_transform(df['SubjectID'])

print(df)

X_columns=[x for x in df.columns if x!='Label']
features=len(X_columns)
model = Sequential()
model.add(LSTM(100, activation='tanh', return_sequences=True, input_shape=(1, features)))
model.add(LSTM(49, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])


grouped=df.groupby('SubjectID')



for group in grouped:
    df_batch=pd.DataFrame(columns=['SubjectID','Feat_1','Feat_2','Feat_X','Hr_count','Label'])
    for subjectID in group:
        filter=df['SubjectID']==subjectID 
        for key,item in df[filter].dropna().iterrows():
            df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
    #print("\n",df_batch)
    X=df_batch[X_columns]
    X = np.resize(X,(X.shape[0],1,X.shape[1]))
    y=df_batch['Label']
    print("\n",X)
    model.fit(X,y,batch_size=len(X), 
          epochs=10)

    SubjectID  Feat_1  Feat_2  Feat_X  Label
0           0      89      31      43      0
1           0      94      32      68      0
2           0      38      90      86      0
3           0      79      34      78      1
4           0      85      24      70      1
5           1       7       9      32      0
6           1      60      56      72      0
7           1      68      72      23      0
8           2      26      88       1      0
9           3      45      27      22      0
10          3      10      80      67      0
11          3      71      48      21      0
12          3      58       9      60      1


C:\Users\DNISHI~1\AppData\Local\Temp/ipykernel_12144/3845206143.py:40: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  filter=df['SubjectID']==subjectID



 [[[ 0. 89. 31. 43.]]

 [[ 0. 94. 32. 68.]]

 [[ 0. 38. 90. 86.]]

 [[ 0. 79. 34. 78.]]

 [[ 0. 85. 24. 70.]]]
Epoch 1/10
1/1 [==============================] - 4s 4s/step - loss: 0.7130 - accuracy: 0.4000
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 0.6794 - accuracy: 0.8000
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6586 - accuracy: 0.8000
Epoch 4/10
1/1 [==============================] - 0s 0s/step - loss: 0.6395 - accuracy: 0.8000
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 0.6191 - accuracy: 0.8000
Epoch 6/10
1/1 [==============================] - 0s 23ms/step - loss: 0.5979 - accuracy: 0.8000
Epoch 7/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5752 - accuracy: 0.8000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5508 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5249 - accuracy: 1.0000
Epoch 10/10
1/1 [=======