In [1]:
import pandas as pd
from io import StringIO
import io
from keras.models import Sequential
from keras.layers import LSTM, Dense
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [7]:
data="""SubjectID,Feat_1,Feat_2,Feat_X,Hr_count,Label
s0001,89,31,43,1,0
s0001,94,32,68,2,0
s0001,38,90,86,3,0
s0001,79,34,78,4,1
s0001,85,24,70,5,1
s0002,7 ,9 ,32,1,0
s0002,60,56,72,2,0
s0002,68,72,23,3,0
s0003,26,88,1 ,1,0
s0004,45,27,22,1,0
s0004,10,80,67,2,0
s0004,71,48,21,3,0
s0004,58,9 ,60,4,1
"""

df=pd.read_csv(io.StringIO(data),sep=",")
df.drop(columns='Hr_count',inplace=True)
encoder=LabelEncoder()
df['SubjectID']=encoder.fit_transform(df['SubjectID'])

print(df)

X_columns=[x for x in df.columns if x!='Label']
features=len(X_columns)
model = Sequential()
model.add(LSTM(100, activation='tanh', return_sequences=True, input_shape=(1, features)))
model.add(LSTM(49, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
history=model.compile(optimizer="rmsprop", loss='binary_crossentropy', metrics=['accuracy'])


grouped=df.groupby('SubjectID')



for group in grouped:
    df_batch=pd.DataFrame(columns=['SubjectID','Feat_1','Feat_2','Feat_X','Hr_count','Label'])
    for subjectID in group:
        filter=df['SubjectID']==subjectID 
        for key,item in df[filter].dropna().iterrows():
            df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
    #print("\n",df_batch)
    X=df_batch[X_columns]
    X = np.asarray(X).astype(np.float32)
    X = np.resize(X,(X.shape[0],1,X.shape[1]))
    y=df_batch['Label']
    y = np.asarray(y).astype(np.float32)
    print("\n",X)
    model.fit(X,y,batch_size=len(X), 
          epochs=10)

    SubjectID  Feat_1  Feat_2  Feat_X  Label
0           0      89      31      43      0
1           0      94      32      68      0
2           0      38      90      86      0
3           0      79      34      78      1
4           0      85      24      70      1
5           1       7       9      32      0
6           1      60      56      72      0
7           1      68      72      23      0
8           2      26      88       1      0
9           3      45      27      22      0
10          3      10      80      67      0
11          3      71      48      21      0
12          3      58       9      60      1

 [[[ 0. 89. 31. 43.]]

 [[ 0. 94. 32. 68.]]

 [[ 0. 38. 90. 86.]]

 [[ 0. 79. 34. 78.]]

 [[ 0. 85. 24. 70.]]]
Epoch 1/10


C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID

1/1 [==============================] - 3s 3s/step - loss: 0.6947 - accuracy: 0.6000
Epoch 2/10
1/1 [==============================] - 0s 5ms/step - loss: 0.6578 - accuracy: 0.6000
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 0.6302 - accuracy: 0.8000
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6020 - accuracy: 0.8000
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5714 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 15ms/step - loss: 0.5385 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 13ms/step - loss: 0.5049 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 19ms/step - loss: 0.4713 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.4396 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 9ms/step - loss: 0.4094 - accuracy: 1.0000

 [[[ 1.  7.  9. 32.]]

 [[ 1. 60. 56. 72.]]

 

C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID

1/1 [==============================] - 2s 2s/step - loss: 0.4887 - accuracy: 1.0000
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 0.3437 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - 0s 15ms/step - loss: 0.2695 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 31ms/step - loss: 0.2192 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 0.1818 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 0.1525 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.1292 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.1103 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0949 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 20ms/step - loss: 0.0821 - accuracy: 1.0000

 [[[ 2. 26. 88.  1.]]]
Epoch 1/10
1/1 [=======

C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:40: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  filter=df['SubjectID']==subjectID


1/1 [==============================] - 0s 6ms/step - loss: 0.0250 - accuracy: 1.0000

 [[[ 3. 45. 27. 22.]]

 [[ 3. 10. 80. 67.]]

 [[ 3. 71. 48. 21.]]

 [[ 3. 58.  9. 60.]]]
Epoch 1/10
1/1 [==============================] - 0s 14ms/step - loss: 0.2820 - accuracy: 0.7500
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 0.1795 - accuracy: 1.0000
Epoch 3/10
1/1 [==============================] - ETA: 0s - loss: 0.1385 - accuracy: 1.0000

C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID':item['SubjectID'],'Feat_1':item['Feat_1'],'Feat_2':item['Feat_2'],'Feat_X':item['Feat_X'],'Label':item['Label']},ignore_index=True)
C:\Users\dnishimoto\AppData\Local\Temp\ipykernel_14632\1730081952.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_batch=df_batch.append({'SubjectID

1/1 [==============================] - 0s 20ms/step - loss: 0.1385 - accuracy: 1.0000
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 0.1136 - accuracy: 1.0000
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 0.0961 - accuracy: 1.0000
Epoch 6/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0831 - accuracy: 1.0000
Epoch 7/10
1/1 [==============================] - 0s 18ms/step - loss: 0.0729 - accuracy: 1.0000
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.0646 - accuracy: 1.0000
Epoch 9/10
1/1 [==============================] - 0s 25ms/step - loss: 0.0577 - accuracy: 1.0000
Epoch 10/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0518 - accuracy: 1.0000


In [ ]:
c