In [2]:
from tensorflow.python.keras.utils import to_categorical
import tensorflow.keras as keras
import numpy as np
from tensorflow.keras.layers import Input, RepeatVector,Dense
from tensorflow.keras.models import Model
from tensorflow.keras.initializers import RandomNormal

C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'

In [4]:
print('reverse the sentence')
def words2onehot(word_list, word2index):
    word_ids=[word2index[w] for w in word_list]
    onehot = to_categorical(word_ids,3)
    return onehot

def encoder(onehot):
    word_ids=np.argmax(onehot,axis=1)
    return word_ids

def decoder(context_vector):
    word_ids_rev = context_vector[::-1]
    onehot_rev = to_categorical(word_ids_rev,3)
    return onehot_rev

def onehot2words(onehot,index2word):
    ids=np.argmax(onehot,axis=1)
    return [index2word[id] for id in ids]

word2index = {"He":0, "drank": 1, "milk": 2}
index2word={}
for k,v in word2index.items():
    index2word[v]=k
onehot = words2onehot(["He","drank","milk"],word2index)
print(onehot)
context=encoder(onehot)
print(context)
onehot=decoder(context)
print(onehot)
output=onehot2words(onehot,index2word)
print(output)

reverse the sentence
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
['milk', 'drank', 'He']


In [42]:
print("You will then use the model to produce output values for a random input array.")
print("batch shape")
inp = keras.layers.Input(batch_shape=(3,3,4))
gru_out = keras.layers.GRU(10)(inp)
# Define a model that outputs the GRU output
model = keras.models.Model(inputs=inp, outputs=gru_out)

x = np.random.normal(size=(3,3,4))
# Get the output of the model and print the result
y = model.predict(x)
print("shape (y) =", y.shape, "\ny = \n", y)


You will then use the model to produce output values for a random input array.
batch shape
shape (y) = (3, 10) 
y = 
 [[-0.0468959   0.38583383 -0.08538818 -0.3008589  -0.14826986 -0.38742658
  -0.26924223  0.19452485 -0.4177479   0.22105226]
 [-0.00633644  0.22847392  0.31598562 -0.37652582 -0.2800822  -0.37632835
  -0.495751    0.18387166 -0.15359062 -0.09455939]
 [-0.01560704  0.06019296  0.0133296  -0.03632982 -0.01499172 -0.01217896
   0.04217295 -0.03592676 -0.04392115  0.01793264]]


In [43]:
print("using shape allows you to dynamic change the batch size")
inp = keras.layers.Input(shape=(3,4))
gru_out,gru_state = keras.layers.GRU(10, return_state=True)(inp)
# Define a model that outputs the GRU output
model = keras.models.Model(inputs=inp, outputs=gru_out)

x = np.random.normal(size=(5,3,4))
# Get the output of the model and print the result
y = model.predict(x)
print("shape (y) =", y.shape, "\ny = \n", y)


using shape allows you to dynamic change the batch size
shape (y) = (5, 10) 
y = 
 [[ 0.28790182 -0.08778092 -0.3947451   0.08208252  0.47034615  0.19104251
   0.5588158   0.19082893  0.34927076  0.20443696]
 [ 0.00722254 -0.00360633  0.21764058  0.20450704 -0.08853464 -0.05885381
   0.1363178   0.05405368 -0.18733037  0.06652743]
 [ 0.15484947  0.02762293 -0.2907805  -0.4547437   0.27811003  0.02760975
   0.07876462  0.20634882  0.37222385 -0.07333589]
 [ 0.00810948  0.01563453 -0.07805486  0.01032428  0.01103292  0.1591216
   0.09145151 -0.1654509   0.12341884  0.18157804]
 [-0.18695843  0.18865353  0.26381043  0.20169011 -0.47334808 -0.03242009
  -0.15041012 -0.21761993 -0.27158606  0.00424054]]


In [51]:
rep=RepeatVector(5)
r_inp=Input(shape=(3,))
r_out = RepeatVector(5)(r_inp)
repeat_model = keras.models.Model(inputs=r_inp, outputs=r_out)
x= np.array([[0,1,2],[3,4,5]])
y=repeat_model.predict(x)
print(y)
print('x.shape = ',x.shape, '\ny.shape =', y.shape)


[[[0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]
  [0. 1. 2.]]

 [[3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]
  [3. 4. 5.]]]
x.shape =  (2, 3) 
y.shape = (2, 5, 3)


In [61]:

en_len = 15
en_vocab = 150
hsize = 48

# Define an input layer
en_inputs = keras.layers.Input(shape=(en_len,en_vocab))
# Define a GRU layer which returns the state
en_gru = keras.layers.GRU(hsize, return_state=True)
# Get the output and state from the GRU
en_out,en_state = en_gru(en_inputs)
# Define and print the model summary
encoder = keras.models.Model(inputs=en_inputs, outputs=en_state)

hsize = 48
fr_len = 20
# Define a RepeatVector layer
de_inputs = RepeatVector(fr_len)(en_state)
# Define a GRU model that returns all outputs
decoder_gru = keras.layers.GRU(hsize, return_sequences=True)
# Get the outputs of the decoder
gru_outputs = decoder_gru(de_inputs, initial_state=en_state)
# Define a model with the correct inputs and outputs
enc_dec = Model(inputs=en_inputs, outputs=gru_outputs)

print(encoder.summary())
print(enc_dec.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_21 (InputLayer)        (None, 15, 150)           0         
_________________________________________________________________
gru_15 (GRU)                 [(None, 48), (None, 48)]  28656     
Total params: 28,656
Trainable params: 28,656
Non-trainable params: 0
_________________________________________________________________
None
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_21 (InputLayer)           (None, 15, 150)      0                                            
__________________________________________________________________________________________________
gru_15 (GRU)                    [(None, 48), (None,  28656       input_21[0][0]                   
__________________________________

In [71]:
init = RandomNormal(mean=0.0, stddev=0.05, seed=6000)
dense = Dense(4, activation='softmax',kernel_initializer=init, bias_initializer=init)
inp = Input (shape=(3,))
pred=dense(inp)
model =Model(inputs=inp, outputs=pred)
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_25 (InputLayer)        (None, 3)                 0         
_________________________________________________________________
dense_5 (Dense)              (None, 4)                 16        
Total params: 16
Trainable params: 16
Non-trainable params: 0
_________________________________________________________________
None
