In [3]:
import tensorflow as tf
tf.enable_eager_execution()
import torch
import torch.nn as nn
import torchvision
import torch.utils.data
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as transforms
import pandas as pd
import numpy as np
from tensorflow.keras.datasets import mnist,cifar10
from PIL import Image
import matplotlib.pyplot as plt
from skimage.transform import rescale,resize

C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'

In [4]:

input_layer=torch.tensor([2.,1.])
weight_1 = torch.tensor([[0.45,0.32],
[-0.12,0.29]])
hidden_layer=torch.matmul(input_layer, weight_1)

weight_2 = torch.tensor([[0.48,-0.12],
[0.64,0.91]])

output_layer=torch.matmul(hidden_layer, weight_2)

print(output_layer)


tensor([0.9696, 0.7527])


In [5]:
weight=torch.matmul(weight_1,weight_2)
print(weight)
output_layer=torch.matmul(input_layer,weight)
print(output_layer)

print('you can use a single layer network with weights and get the same results')

tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])
tensor([0.9696, 0.7527])
you can use a single layer network with weights and get the same results


In [6]:
relu=nn.ReLU()
tensor_1=torch.tensor([2.,4.])
print(relu(tensor_1))
tensor_2=torch.tensor([[2.,4.],[1.2,0]])
print(relu(tensor_2))

tensor([2., 4.])
tensor([[2.0000, 4.0000],
        [1.2000, 0.0000]])


In [7]:
input_layer=torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

weight_1=torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])


weight_2=torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])


weight_3=torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])

# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


In [8]:
# Apply non-linearity on hidden_1 and hidden_2
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

print("Results are different")

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])
Results are different


In [9]:
val=np.log(-1.2)*-1+np.log(.12)+np.log(4.8)
print(np.log(4.8))


1.5686159179138452


C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


In [10]:
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits,ground_truth)
print(loss)





tensor(0.0117)


In [11]:
#(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()


In [12]:
#(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
transform=transforms.Compose(
    [transforms.ToTensor(),
        transforms.Normalize(
                    (0.4914,0.48216,0.44653),
                    (0.24703,0.24349,0.26159)
                            )])

trainset=torchvision.datasets.CIFAR10(root='./data',train=True, download=True, transform=transform)
testset=torchvision.datasets.CIFAR10(root='./data',train=False, download=True, transform=transform)


Files already downloaded and verified
Files already downloaded and verified


In [13]:
trainloader=torch.utils.data.DataLoader(trainset, batch_size=32, shuffle=False, num_workers=2)
testloader=torch.utils.data.DataLoader(testset, batch_size=32, shuffle=False, num_workers=2)
#print(testloader.dataset.test_data.shape, trainload.dataset.train_data.shape)
print(trainloader.batch_size,testloader.batch_size)

32 32


In [14]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1=nn.Linear(32*32*3,500) #input layer of 32x32 pixel by 3 color channels with 500 neurons in the hidden layer
        self.fc2=nn.Linear(500,10)
#10 output classes

    def forward(self,x):
        x=F.relu(self.fc1(x))
        return self.fc2(x)


In [15]:
net=Net()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=3e-4)

correct,total=0,0
predictions=[]
for epoch in range(10):
    print("epoch",epoch)
    net.train()
    for i, data in enumerate(trainloader,0):
        inputs,labels=data
        inputs=inputs.view(-1,32*32*3)

        optimizer.zero_grad()

        
        outputs=net(inputs)
        loss=criterion(outputs,labels)
        loss.backward()
        optimizer.step()  #adjust weights

        __,predicted=torch.max(outputs.data,1)
        predictions.append(outputs)
        total+=labels.size(0)
        correct+=(predicted==labels).sum().item()

print("The testing set accuracy of the network is %d %%" % (100*correct/total))

epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
The testing set accuracy of the network is 60 %


In [17]:
correct,total=0,0
predictions=[]
IMG_SIZE=32
for epoch in range(10):
    print("Epoch",epoch)
    for i, data in enumerate(testloader,0):
        inputs,labels=data
        inputs=inputs.view(-1,32*32*3)
        outputs=net(inputs)
        __,predicted=torch.max(outputs.data,1)
        total += labels.size(0)
        correct+=(predicted==labels).sum().item()

print("The testing set accuracy of the network is %d %%" % (100*correct/total))


Epoch 0
Epoch 1
Epoch 2
Epoch 3
Epoch 4
Epoch 5
Epoch 6
Epoch 7
Epoch 8
Epoch 9
The testing set accuracy of the network is 51 %


In [18]:
from skimage.transform import rescale,resize
# Set the model in eval mode
net.eval()

#data = X_train[1, :] # get a row data
#data = np.reshape(data, (32,32,3), order='F' ) # Fortran-like indexing order
#plt.imshow(data)
#plt.show()

plt.clf()
for i, data in enumerate(testloader, 0):
    inputs, targets = data
    
    # Put each image into a vector
    inputs_view = inputs.view(-1, 32*32*3)

    #for i in range(len(inputs_view)):
    #    image=inputs_view[i,:]
    #    image = np.reshape(image, (32,32,3), order='F' ) # Fortran-like indexing order
    #    plt.imshow(image)  #,interpolation='nearest'
    #    plt.show()    

    
    # Do the forward pass and get the predictions
    outputs = net(inputs_view)
    _, outputs = torch.max(outputs.data, 1)
    total += targets.size(0)
    correct += (outputs == targets).sum().item()
print('The testing set accuracy of the network is: %d %%' % (100 * correct / total))

The testing set accuracy of the network is: 51 %


<Figure size 432x288 with 0 Axes>

In [19]:
#https://medium.com/swlh/image-classification-with-cnn-4f2a501faadb
class CNN_Net(nn.Module):
    def __init__(self,num_classes=10):
        super(CNN_Net, self).__init__()
        self.features = nn.Sequential(
        # Instantiate two convolutional layers
        #self.conv1 = nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, padding=1)
        #self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
       # self.conv3 = nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, padding=1)
        nn.Conv2d(3,32, kernel_size=3, padding=1),
        nn.ReLU(),            
        nn.Conv2d(32,64, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2, 2), #64x16x16       
        # The feature map gets smaller as we add more layers, until we are finally left 
        # with a small feature map, which can be flattened into a vector.             
        nn.Conv2d(64,128, kernel_size=3,stride=1, padding=1),
        nn.ReLU(),
        nn.Conv2d(128,128, kernel_size=3,stride=1, padding=1),            
        nn.ReLU(),            
        nn.MaxPool2d(2, 2), #128x8x8
        nn.Conv2d(128, 256, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),            
        nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
        nn.ReLU(),
        nn.MaxPool2d(2, 2), # output: 256 x 4 x 4
        )
        # Instantiate the ReLU nonlinearity
        #self.relu = nn.ReLU()
        
        # Instantiate a max pooling layer
        #self.pool = nn.MaxPool2d(2, 2)
        
        # Instantiate a fully connected layer
        self.classifier = nn.Sequential(
            nn.Flatten(), 
            nn.Linear(256*4*4, 1024),
            nn.ReLU(),
            nn.Linear(1024,512),
            nn.ReLU(),
            nn.Linear(512,num_classes)
        
            )  #fully connect layer  = units of the last layer   4= 32/2*3 where 2 is the pool and 3 is the kernel

    def forward(self, x):
        # Apply the feature extractor in the input
        x = self.features(x)
        #x=x.view(-1,32*32*3)
          # Classify the images
        x = self.classifier(x)
        return x
        #x=self.pool(F.relu(self.conv1(x)))
        #x=self.pool(F.relu(self.conv2(x)))
        #x=self.pool(F.relu(self.conv3(x)))
        #x=x.view(-1,128*4*4)
        #return self.fc(x)

In [20]:
net = CNN_Net()
criterion=nn.CrossEntropyLoss()
optimizer=optim.Adam(net.parameters(), lr=3e-4)

net.train()
for epoch in range(10):
    print("Epoch",epoch)
    for i, data in enumerate(trainloader,0):
        net.train()
        inputs,labels=data
        optimizer.zero_grad()
        #inputs=inputs.view(-1,128*4*4)
        outputs=net(inputs)
        loss=criterion(outputs,labels)
        loss.backward()
        optimizer.step()
    

print('Finished Training')


Epoch 0
Epoch 1
Epoch 2


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-06551e62a2c5>", line 14, in <module>
    loss.backward()
  File "C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\torch\tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\torch\autograd\__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\IPython\core\i

TypeError: object of type 'NoneType' has no len()

In [21]:
correct,total=0,0
predictions=[]
net.eval()
for epoch in range(10):
    for i, data in enumerate(testloader,0):
        inputs,labels=data
        outputs=net(inputs)
        __,predicted=torch.max(outputs.data,1)
        predictions.append(outputs)
        total += labels.size(0)
        correct+=(predicted==labels).sum().item()

print("The testing set accuracy of the network is %d %%" % (100*correct/total))


RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 4194304 bytes. Buy new RAM!