In [5]:
import tensorflow as tf
tf.enable_eager_execution()
import torch
import torch.nn as nn
import torchvision
import torch.utils.data
import torchvision.transforms as transforms
import pandas as pd
import numpy as np
from tensorflow.keras.datasets import mnist,cifar10

In [34]:

input_layer=torch.tensor([2.,1.])
weight_1 = torch.tensor([[0.45,0.32],
[-0.12,0.29]])
hidden_layer=torch.matmul(input_layer, weight_1)

weight_2 = torch.tensor([[0.48,-0.12],
[0.64,0.91]])

output_layer=torch.matmul(hidden_layer, weight_2)

print(output_layer)


tensor([0.9696, 0.7527])


In [3]:
weight=torch.matmul(weight_1,weight_2)
print(weight)
output_layer=torch.matmul(input_layer,weight)
print(output_layer)

print('you can use a single layer network with weights and get the same results')

tensor([[0.4208, 0.2372],
        [0.1280, 0.2783]])
tensor([0.9696, 0.7527])
you can use a single layer network with weights and get the same results


In [4]:
relu=nn.ReLU()
tensor_1=torch.tensor([2.,4.])
print(relu(tensor_1))
tensor_2=torch.tensor([[2.,4.],[1.2,0]])
print(relu(tensor_2))

tensor([2., 4.])
tensor([[2.0000, 4.0000],
        [1.2000, 0.0000]])


In [5]:
input_layer=torch.tensor([[ 0.0401, -0.9005,  0.0397, -0.0876]])

weight_1=torch.tensor([[-0.1094, -0.8285,  0.0416, -1.1222],
        [ 0.3327, -0.0461,  1.4473, -0.8070],
        [ 0.0681, -0.7058, -1.8017,  0.5857],
        [ 0.8764,  0.9618, -0.4505,  0.2888]])


weight_2=torch.tensor([[ 0.6856, -1.7650,  1.6375, -1.5759],
        [-0.1092, -0.1620,  0.1951, -0.1169],
        [-0.5120,  1.1997,  0.8483, -0.2476],
        [-0.3369,  0.5617, -0.6658,  0.2221]])


weight_3=torch.tensor([[ 0.8824,  0.1268,  1.1951,  1.3061],
        [-0.8753, -0.3277, -0.1454, -0.0167],
        [ 0.3582,  0.3254, -1.8509, -1.4205],
        [ 0.3786,  0.5999, -0.5665, -0.3975]])

# Calculate the first and second hidden layer
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

# Calculate the output
print(torch.matmul(hidden_2, weight_3))

# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[0.2653, 0.1311, 3.8219, 3.0032]])
tensor([[0.2653, 0.1311, 3.8219, 3.0032]])


In [6]:
# Apply non-linearity on hidden_1 and hidden_2
hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

# Apply non-linearity in the product of first two weights. 
weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

print("Results are different")

tensor([[-0.2770, -0.0345, -0.1410, -0.0664]])
tensor([[-0.2117, -0.4782,  4.0438,  3.0417]])
Results are different


In [18]:
val=np.log(-1.2)*-1+np.log(.12)+np.log(4.8)
print(np.log(4.8))


1.5686159179138452


C:\Users\dnishimoto.BOISE\AppData\Local\Continuum\anaconda3\envs\deeplearning\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


In [23]:
logits = torch.tensor([[-1.2, 0.12, 4.8]])
ground_truth = torch.tensor([2])

# Instantiate cross entropy loss
criterion = nn.CrossEntropyLoss()

# Compute and print the loss
loss = criterion(logits,ground_truth)
print(loss)





tensor(0.0117)


In [6]:
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()



In [9]:
#(X_train, Y_train), (X_test, Y_test) = cifar10.load_data()
transform=transforms.Compose(
    [transforms.ToTensor(),
        transforms.Normalize(
                    (0.4914,0.48216,0.44653),
                    (0.24703,0.24349,0.26159)
                            )])

trainset=torchvision.datasets.CIFAR10(root='./data',train=True, download=True, transform=transform)
testset=torchvision.datasets.CIFAR10(root='./data',train=False, download=True, transform=transform)


Files already downloaded and verified
Files already downloaded and verified


In [20]:
testloader=torch.utils.data.DataLoader(testset, batch_size=32, shuffle=False, num_workers=2)

#print(testloader.dataset.test_data.shape, trainload.dataset.train_data.shape)
print(testloader.batch_size)

32
