In [7]:
import torch
import torch.nn as nn

#http://yann.lecun.com/exdb/mnist/

input_layer = torch.rand(10)
w1=torch.rand(10,20)
w2=torch.rand(20,20)
w3=torch.rand(20,4)

h1=torch.matmul(input_layer, w1)
h2=torch.matmul(h1,w2)
output_layer=torch.matmul(h2,w3)
print(output_layer)


tensor([240.5046, 267.4117, 257.5000, 260.7034])


In [5]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1=nn.Linear(10,20)
        self.fc2=nn.Linear(20,20)
        self.output=nn.Linear(20,4)
    
    def forward(self,x):
        x=self.fc1(x)
        x=self.fc2(x)
        x=self.output(x)
        return x

input_layer=torch.rand(10)
net=Net()
result=net(input_layer)
print(result)

tensor([ 0.2117,  0.2828, -0.0384, -0.1271], grad_fn=<AddBackward0>)


In [11]:
# Initialize the weights of the neural network
input_layer= torch.rand(784,784)
weight_1 = torch.rand(784, 200)
weight_2 = torch.rand(200, 10)

# Multiply input_layer with weight_1
hidden_1 = torch.matmul(input_layer, weight_1)

# Multiply hidden_1 with weight_2
output_layer = torch.matmul(hidden_1, weight_2)
print(output_layer)

tensor([[20704.0742, 19473.7363, 18989.6855,  ..., 19715.6836, 19278.0742,
         20966.0625],
        [20217.0859, 18997.7188, 18544.8848,  ..., 19248.5371, 18799.7539,
         20445.1426],
        [20468.4805, 19254.8887, 18759.5098,  ..., 19484.4668, 19070.3828,
         20723.8984],
        ...,
        [20464.5234, 19261.2070, 18746.8301,  ..., 19485.3398, 19059.1094,
         20717.1582],
        [20641.3555, 19414.8867, 18931.8125,  ..., 19679.8379, 19263.7305,
         20916.8164],
        [20769.0449, 19543.3555, 19053.4102,  ..., 19780.2617, 19362.2695,
         21016.3594]])
